name: Delete Logs from GCP Instance

on:
  workflow_dispatch:
    inputs:
      project_id:
        description: 'GCP Project ID'
        required: true
      instance_name:
        description: 'GCP Instance Name'
        required: true
      zone:
        description: 'GCP Zone'
        required: true
      logs_path:
        description: 'Path to Logs on the Instance'
        required: true

jobs:
  delete-logs:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ github.event.inputs.project_id }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Get Instance IP Address
      id: get-instance-ip
      run: |
        INSTANCE_IP=$(gcloud compute instances describe ${{ github.event.inputs.instance_name }} \
          --zone ${{ github.event.inputs.zone }} \
          --format='get(networkInterfaces[0].accessConfigs[0].natIP)')
        echo "INSTANCE_IP=${INSTANCE_IP}" >> $GITHUB_ENV

    - name: Delete .log Files from the Instance
      run: |
        gcloud compute ssh root@${{ env.INSTANCE_IP }} \
          --zone ${{ github.event.inputs.zone }} \
          --command "sudo rm -f ${{ github.event.inputs.logs_path }}/*.log"
