name: Delete Logs on GCP Instance

on:
  workflow_dispatch:
    inputs:
      instance_name:
        description: 'Name of the GCP Compute instance'
        required: true
      logs_path:
        description: 'Path to the logs on the GCP Compute instance'
        required: true

jobs:
  delete_logs:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authorize SSH Key
        run: |
          gcloud compute config-ssh --quiet

      - name: Delete log files on GCP instance via SSH
        run: |
          gcloud compute ssh ${{ github.event.inputs.instance_name }} \
            --zone ${{ secrets.GCP_ZONE }} \
            --command "sudo rm -f '${{ github.event.inputs.logs_path }}/*.log'"
