name: Sync Database Dump to GCP Bucket

on:
  workflow_dispatch:
    inputs:
      instance_name:
        description: 'Name of the GCP instance'
        required: true
      bucket_name:
        description: 'GCP bucket name'
        required: true
      dump_file_path:
        description: 'Path to the directory containing the .sql files'
        required: true

jobs:
  sync-dump:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: 'latest'

    - name: List GCP instances
      run: |
        echo "Listing GCP instances..."
        gcloud compute instances list --filter="name=${{ github.event.inputs.instance_name }}"

    - name: SSH into GCP instance and upload .sql files
      run: |
        echo "SSH into the instance: ${{ github.event.inputs.instance_name }}"
        gcloud compute ssh ${{ github.event.inputs.instance_name }} --command "
          sql_files=\$(find ${{ github.event.inputs.dump_file_path }} -name '*.sql')
          for file in \$sql_files; do
            echo \"Uploading \$file to gs://${{ github.event.inputs.bucket_name }}/\"
            gsutil cp \"\$file\" gs://${{ github.event.inputs.bucket_name }}/
          done
        "
