name: Sync Database Dump to GCP Bucket

on:
  workflow_dispatch:
    inputs:
      dump_file_path:
        description: 'Path to the database dump file'
        required: true
      bucket_name:
        description: 'GCP bucket name'
        required: true

jobs:
  sync-dump:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCP_SA_DB_KEY }}
        export_default_credentials: true

    - name: Authenticate with Service Account
      run: |
        echo "${{ secrets.GCP_SA_DB_KEY }}" > "${{ runner.temp }}/account.json"
        gcloud auth activate-service-account --key-file="${{ runner.temp }}/account.json"
        gcloud config set project YOUR_PROJECT_ID

    - name: Sync database dump to GCP bucket
      run: |
        gsutil cp ${{ github.event.inputs.dump_file_path }} gs://${{ github.event.inputs.bucket_name }}/
