name: Upload SQL Files to GCS

on:
  workflow_dispatch:

jobs:
  upload-sql-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.TEMP_SECRET_KEY }}

      - name: Set up SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: SSH into the instance and upload SQL files
        run: |
          echo "SSH into the instance: ${{ secrets.INSTANCE_NAME }} in zone ${{ secrets.ZONE }}"
          gcloud compute ssh ${{ secrets.SSH_USER }}@${{ secrets.INSTANCE_NAME }} --zone="${{ secrets.ZONE }}" --ssh-key-file=~/.ssh/id_rsa --command "
          cd ${{ secrets.DUMP_FILE_PATH }}
          sql_files=\$(find . -name '*.sql')
          for file in \$sql_files; do
              echo \"Uploading \$file to gs://${{ secrets.BUCKET_NAME }}/\"
              gcloud storage cp \"\$file\" gs://${{ secrets.BUCKET_NAME }}/
          done
          "
