name: Sync Database Dump to GCP Bucket

on:
  workflow_dispatch:
    inputs:
      instance_name:
        description: 'Name of the GCP instance'
        required: true
      zone:
        description: 'Zone of the GCP instance'
        required: true
      bucket_name:
        description: 'GCP bucket name'
        required: true
      dump_file_path:
        description: 'Path to the directory containing the .sql files'
        required: true

jobs:
  sync-dump:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCP_SA_DB_KEY }}
        export_default_credentials: true

    - name: SSH into the instance and list .sql files
      run: |
        echo "SSH into the instance and list .sql files:"
        gcloud compute ssh ${{ github.event.inputs.instance_name }} --zone=${{ github.event.inputs.zone }} --command="ls ${{ github.event.inputs.dump_file_path }}/*.sql" > sql_files_list.txt

    - name: Copy .sql files to GCP bucket
      run: |
        echo "Copying .sql files to GCP bucket:"
        while IFS= read -r file; do
          if [ -n "$file" ]; then
            echo "Copying $file to gs://${{ github.event.inputs.bucket_name }}/"
            gcloud compute scp ${{ github.event.inputs.instance_name }}:${file} gs://${{ github.event.inputs.bucket_name }}/ --zone=${{ github.event.inputs.zone }}
          fi
        done < sql_files_list.txt
