name: Fetch Secret from Google Secret Manager

on:
  workflow_dispatch:
    inputs:
      secret_name:
        description: 'The name of the secret to fetch'
        required: true
        default: 'test-creds'

jobs:
  fetch-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
          credentials: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set GCP Project
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Fetch Secret from Secret Manager
        id: fetch_secret
        run: |
          gcloud secrets versions access latest --secret="${{ github.event.inputs.secret_name }}" > secret.txt

      - name: Display Secret
        run: |
          cat secret.txt
