name: Fetch Secret from Google Secret Manager

on:
  push:
    branches:
      - main

jobs:
  fetch-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
          credentials: ${{ secrets.GCP_CREDENTIALS }}

      - name: Fetch Secret from Secret Manager
        id: fetch_secret
        run: |
          gcloud secrets versions access latest --secret="test-creds" > secret.txt
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

      - name: Display Secret
        run: |
          cat secret.txt
