name: Test WIF

on:
  workflow_dispatch:
    inputs:
      TAG_NAME:
        description: 'Tag name of the server to restart'
        required: true
      ZONE:
        description: 'The GCP zone of the server'
        required: true
        
permissions:  
  id-token: write  
  contents: read

jobs:
  restart-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
           token_format: 'access_token'
           workload_identity_provider: "projects/976604417255/locations/global/workloadIdentityPools/github-actions-identity-pool-2/providers/github-actions-provider"
           service_account: "976604417255-compute@developer.gserviceaccount.com"

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Find Instance by Tag
        id: find-instance
        run: |
          echo "Looking for instance with tag '${{ github.event.inputs.TAG_NAME }}' in zone '${{ github.event.inputs.ZONE }}'..."
          INSTANCE_NAME=$(gcloud compute instances list \
            --filter="labels.name=${{ github.event.inputs.TAG_NAME }}" \
            --format="get(name)" --zones="${{ github.event.inputs.ZONE }}")
          
          if [ -z "$INSTANCE_NAME" ]; then
            echo "No instance found with the tag '${{ github.event.inputs.TAG_NAME }}' in zone '${{ github.event.inputs.ZONE }}'."
            exit 1
          fi

          echo "Found instance: $INSTANCE_NAME"
          echo "INSTANCE_NAME=$INSTANCE_NAME" >> $GITHUB_ENV

      - name: Stop the Instance
        run: |
          echo "Stopping instance: $INSTANCE_NAME"
          gcloud compute instances stop "$INSTANCE_NAME" \
            --zone="${{ github.event.inputs.ZONE }}"

      - name: Start the Instance
        run: |
          echo "Starting instance: $INSTANCE_NAME"
          gcloud compute instances start "$INSTANCE_NAME" \
            --zone="${{ github.event.inputs.ZONE }}"

      - name: Success Message
        run: echo "Instance $INSTANCE_NAME has been successfully restarted."
